app_group:
  - read:
      path: /apps/timing.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/{name}/_topology
      method: POST

patch:
  - update:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.timing.v1alpha1.ntp_client:
  - create:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients
      method: POST
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/{name}
      method: GET
  - update:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/{name}
      method: PUT

com.nokia.eda.timing.v1alpha1.ntp_client_list:
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients
      method: GET
  - delete:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients
      method: DELETE
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1/ntpclients
      method: GET

com.nokia.eda.timing.v1alpha1.ntp_client_deleted_resources:
  - read:
      path: /apps/timing.eda.nokia.com/v1alpha1/namespaces/{namespace}/ntpclients/_deleted
      method: GET

totalPaths: 10
totalSchemas: 54
usedSchemas: 12
unusedSchemas: 42
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - com.nokia.eda.timing.v1alpha1.NTPClient_DeletedResourceEntry
  - com.nokia.eda.timing.v1alpha1.NTPClient_alarms
  - com.nokia.eda.timing.v1alpha1.NTPClient_deviations
  - com.nokia.eda.timing.v1alpha1.NTPClient_metadata
